server:
  port: 8082

spring:
  application:
    name: warehouse-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sparrow
      auto-index-creation : true

jwt:
  secret: "change-this-to-a-very-long-random-secret-at-least-32-characters"
  expirationMillis: 3600000