server:
  port: 8083
spring:
  application:
    name: parcel-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sparrow
jwt:
  secret: "REPLACE_WITH_BASE64_SECRET"
  expirationMillis: 3600000

logging:
  level:
    com.sparrow.parcel_service: DEBUG
