server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sparrow


jwt:
  secret: "REPLACE_WITH_BASE64_SECRET"
  expirationMillis: 3600000


logging:
  level:
    org.springframework.security: DEBUG