spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092}  # fallback to kafka:9092
    consumer:
      group-id: parcel-tracking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
