spring:
  data:
    mongodb:
      host: ${MONGO_HOST:mongodb}   # fallback to mongodb
      port: ${MONGO_PORT:27017}    # fallback to 27017
      database: ${MONGO_DB:parceldb}
      username: ${MONGO_USER:parcel_user}
      password: ${MONGO_PASS:secret}
